FROM node:20-alpine
WORKDIR /app

# Copy package files and install
COPY services/api-gateway/package*.json ./
RUN npm install

# Copy the source code
COPY services/api-gateway/ .

# Expose the gateway port
EXPOSE 4000

CMD ["node", "app.js"]